name: Build and Upload Docker Image

on:
  push:
    branches:
      - main  # 触发条件，可以根据需要修改

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image using docker-compose
        run: |
          docker-compose build

      - name: Save Docker image as tar
        run: |
          docker save -o stockanal_sys.tar stockanal_sys

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: stockanal_sys.tar

  test-compose:
    runs-on: ubuntu-latest
    needs: build  # 依赖 build 任务
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download built Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: |
          docker load -i stockanal_sys.tar

      - name: Start services using docker-compose
        run: |
          docker-compose up -d
          sleep 10  # 等待服务启动
          docker-compose ps  # 检查容器状态
          docker logs $(docker ps -q -f name=stockanal_sys)  # 输出 Flask 日志
          docker-compose down
